export const SITE_URL = "https://samhithreddysangam.portfolio.next360.in/";

export const SITE_ORIGIN = SITE_URL.replace(/\/$/, "");

export const site = {
  name: "Samhith Reddy Sangam",
  shortName: "Samhith Reddy Sangam",
  title: "Samhith Reddy Sangam | Founder & CEO of NEXT360",
  description:
    "Samhith Reddy Sangam is the Founder & CEO of NEXT360 Organic Products Pvt. Ltd., building India's organic commerce infrastructure. This is his official website — portfolio, projects, press coverage and writing on technology, agriculture and entrepreneurship.",
  locale: "en_IN",
  location: {
    city: "Karimnagar",
    region: "Telangana",
    country: "India",
  },
  email: "ceo.office@gmail.com",
  socials: {
    linkedin: "https://www.linkedin.com/in/samhithreddysangam",
    github: "https://github.com/samhithreddysangam",
    calendly: "https://calendly.com/samhithreddysangam",
    next360: "https://next360.in",
  },
  keywords: [
    "samhithreddysangam",
    "Samhith Reddy Sangam",
    "SamhithReddy Sangam",
    "samhithreddy sangam",
    "SamhithReddySangam",
    "Samith Reddy",
    "Sangem Samith Reddy",
    "Samhith Reddy",
    "Samhith Sangam",
    "Samhith Reddy Sangam NEXT360",
    "Samhith Reddy Sangam founder",
    "SamhithReddy entrepreneur",
    "SamhithReddy founder",
    "SamhithReddy Next360",
    "Next360 Organic Products founder",
    "young entrepreneur India",
    "technology entrepreneur India",
    "agriculture technology entrepreneur",
    "digitalising agriculture",
    "technology for farmers",
    "organic products entrepreneur",
    "agriculture innovation India",
    "sustainable agriculture",
    "digital agriculture",
    "farmer empowerment through technology",
    "Samhith Reddy Sangam Karimnagar",
    "Samhith Reddy Sangam Telangana",
    "samhithreddysangam Karimnagar",
    "NEXT360",
    "NEXT360 Organic Products",
    "NEXT360 founder",
    "samhithreddysangam portfolio",
    "Civil Engineer turned Founder",
    "T-Hub incubated founder",
    "organic commerce India",
    "organic startup India",
    "tech founder India",
    "AgriTech founder India",
  ],
} as const;
