export const SITE_URL = "https://samhithreddysangam.portfolio.next360.in/";

export const SITE_ORIGIN = SITE_URL.replace(/\/$/, "");

export const site = {
  name: "SamhithReddy Sangam",
  shortName: "SamhithReddy Sangam",
  title: "SamhithReddy Sangam | Founder & CEO, NEXT360 Organic Products Pvt. Ltd.",
  description:
    "SamhithReddy Sangam is a Civil Engineer turned Tech Founder and Founder & CEO of NEXT360 Organic Products Pvt. Ltd., building India's organic commerce infrastructure. T-Hub incubated entrepreneur, Guinness World Record holder (Agentathon 2025) and DevFest 2025 speaker, based in Karimnagar, Telangana, India.",
  locale: "en_IN",
  location: {
    city: "Karimnagar",
    region: "Telangana",
    country: "India",
  },
  email: "ceo.office@gmail.com",
  socials: {
    linkedin: "https://www.linkedin.com/in/samhithreddysangam",
    github: "https://github.com/samhithreddysangam",
    calendly: "https://calendly.com/samhithreddysangam",
    next360: "https://next360.in",
  },
  keywords: [
    "SamhithReddy Sangam",
    "SamhithReddy entrepreneur",
    "SamhithReddy founder",
    "SamhithReddy Next360",
    "Samhith Reddy Sangam",
    "samhithreddy sangam",
    "Samhith Reddy",
    "Samhith Sangam",
    "Next360 Organic Products founder",
    "young entrepreneur India",
    "technology entrepreneur India",
    "agriculture technology entrepreneur",
    "digitalising agriculture",
    "technology for farmers",
    "organic products entrepreneur",
    "agriculture innovation India",
    "sustainable agriculture",
    "digital agriculture",
    "farmer empowerment through technology",
    "SamhithReddy Sangam Karimnagar",
    "SamhithReddy Sangam Telangana",
    "NEXT360",
    "NEXT360 Organic Products",
    "NEXT360 founder",
    "SamhithReddy portfolio",
    "Civil Engineer turned Founder",
    "T-Hub incubated founder",
    "organic commerce India",
    "organic startup India",
    "tech founder India",
    "AgriTech founder India",
  ],
} as const;
